name = "remix-edge-kit"
type = "javascript"
compatibility_date = "2022-01-28"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build-worker"
watch_dir = "build"

[build.upload]
format="service-worker"
